# Site settings
title_left    : "YetAnother"
title_right   : "MathBlog" # default: ""
description   : "Yet another math blog, by Gabriel Pinochet Soto. Just some random observations related to my work and passion."
keywords      : "Math, analysis, FEM, blog"
domain        : homeomorfismo.github.io/
url           : https://homeomorfismo.github.io/ # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : # UA-XXXXX-XX
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
kramdown:
    math_engine: katex
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Gabriel Pinochet Soto"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-katex

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
